# Changes here will be overwritten by Copier
_commit: fa27c8d
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: t.paine154@gmail.com
github: python-project-templates
project_description: Easily generate sphinx documentation
project_name: yardang
python_version_primary: '3.11'
team: the yardang authors
